import type { Metadata } from "next";
import {  Inter } from "next/font/google";
import "./globals.css";
import LayoutClient from './components/LayoutClient';
import Providers from "@/components/Providers";

const inter = Inter({
  variable: "--font-inter-sans",
  subsets: ["latin"],
});


export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {

  return (
    <html
      lang="en"
      className={`${inter.variable}  h-full antialiased`}
    >
      <body className="min-h-full flex ">
        <LayoutClient>
        <Providers>{children}</Providers>
        </LayoutClient>

      </body>
    </html>
  );
}
